[tool.bandit]
# Bandit security linter configuration
exclude_dirs = ["/tests/", "/test_*.py", "/__pycache__/"]
# Skip common false positives in system automation code
skips = [
    "B101",  # assert_used in tests
    "B102",  # exec_used (used for diagnostic scripts)
    "B103",  # set_bad_file_permissions (scripts need 755)
    "B104",  # hardcoded_bind_all_interfaces (0.0.0.0 needed for API)
    "B110",  # try_except_pass (many cleanup handlers use this intentionally)
    "B310",  # urllib_urlopen (safe - only localhost health checks)
    "B404",  # subprocess import (required for system integration)
    "B602",  # subprocess_popen_with_shell_equals_true (safe - controlled inputs)
    "B603",  # subprocess without shell (safe - we control all inputs)
    "B607",  # partial path (python3 is in PATH)
    "B608",  # hardcoded_sql_expressions (false positive - bash script not SQL)
]

[tool.black]
line-length = 100
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 100
