"""
Context Intelligence Module
============================

Provides intelligent task execution and automation capabilities.
"""

from .executors import get_document_writer, parse_document_request, DocumentRequest
from .automation import get_browser_controller, get_google_docs_client, get_claude_streamer
from .managers import (
    get_space_state_manager,
    initialize_space_state_manager,
    SpaceState,
    SpaceStateInfo,
    EdgeCaseResult,
    get_window_capture_manager,
    initialize_window_capture_manager,
    CaptureStatus,
    CaptureResult,
    get_system_state_manager,
    initialize_system_state_manager,
    YabaiState,
    DisplayState,
    SystemHealth,
    SystemStateInfo,
    get_api_network_manager,
    initialize_api_network_manager,
    APIState,
    NetworkState,
    APIStatus,
    NetworkStatus,
    ImageOptimizationResult,
    RetryResult,
    get_error_handling_matrix,
    initialize_error_handling_matrix,
    FallbackChain,
    ExecutionReport,
    ResultQuality,
    ErrorMessageGenerator,
    get_capture_strategy_manager,
    initialize_capture_strategy_manager,
    CaptureStrategyManager,
)
from .managers import (
    get_ocr_strategy_manager,
    initialize_ocr_strategy_manager,
    OCRStrategyManager,
    OCRCache,
    CachedOCR,
    OCRResult,
)
from .handlers import (
    get_query_complexity_manager,
    initialize_query_complexity_manager,
    QueryComplexityManager,
    QueryComplexityClassifier,
    QueryRouter,
    ClassifiedQuery,
    ComplexityMetrics,
    QueryComplexity,
)

__all__ = [
    "get_document_writer",
    "parse_document_request",
    "DocumentRequest",
    "get_browser_controller",
    "get_google_docs_client",
    "get_claude_streamer",
    "get_space_state_manager",
    "initialize_space_state_manager",
    "SpaceState",
    "SpaceStateInfo",
    "EdgeCaseResult",
    "get_window_capture_manager",
    "initialize_window_capture_manager",
    "CaptureStatus",
    "CaptureResult",
    "get_system_state_manager",
    "initialize_system_state_manager",
    "YabaiState",
    "DisplayState",
    "SystemHealth",
    "SystemStateInfo",
    "get_api_network_manager",
    "initialize_api_network_manager",
    "APIState",
    "NetworkState",
    "APIStatus",
    "NetworkStatus",
    "ImageOptimizationResult",
    "RetryResult",
    "get_error_handling_matrix",
    "initialize_error_handling_matrix",
    "FallbackChain",
    "ExecutionReport",
    "ResultQuality",
    "ErrorMessageGenerator",
    "get_capture_strategy_manager",
    "initialize_capture_strategy_manager",
    "CaptureStrategyManager",
    "get_ocr_strategy_manager",
    "initialize_ocr_strategy_manager",
    "OCRStrategyManager",
    "OCRCache",
    "CachedOCR",
    "OCRResult",
    "get_query_complexity_manager",
    "initialize_query_complexity_manager",
    "QueryComplexityManager",
    "QueryComplexityClassifier",
    "QueryRouter",
    "ClassifiedQuery",
    "ComplexityMetrics",
    "QueryComplexity",
]
